## CONDUCTORS 

### Recuperar lista de conductores
GET http://localhost:7070/api/v1/conductors

### Recuperar conductor por id
GET http://localhost:7070/api/v1/conductors/6691fdca-7548-4c3d-8703-3846b2d8a0cd

### Crear un conductor
POST http://localhost:7070/api/v1/conductors
Content-Type: application/json

{
  "name": "Julio A.",
  "mobilePhone": "3333-000000",
  "serviceGroup": 3,
  "privilege": "QUALIFIED_BROTHER"
}

### Actualizar un conductor
PATCH http://localhost:7070/api/v1/conductors/7aa6cb01-ebcf-4ccb-838d-dc23c1836e67
Content-Type: application/json

{
  "name": "Julio Amoroso",
  "mobilePhone": "1111-000000",
  "serviceGroup": 1,
  "privilege": "GROUP_SERVANT"
}

### Borrar un conductor
DELETE http://localhost:7070/api/v1/conductors/5d74a457-bcc3-435e-9418-fce7ad39da68


### Reemplazar disponibilidad del conductor
PUT http://localhost:7070/api/v1/conductors/7aa6cb01-ebcf-4ccb-838d-dc23c1836e67/availability
Content-Type: application/json

{
  "SATURDAY": { "frequency": "2 week", "moment": "MORNING" },
  "TUESDAY": { "frequency": "every", "moment": "AFTERNOON" }
}

### Borrar disponiblidad del conductor
DELETE http://localhost:7070/api/v1/conductors/6691fdca-7548-4c3d-8703-3846b2d8a0cd/availability