export const PROGRAMS_FOR_PAGE = 2;
export const PROGRAM_CURSOR_INDEX = PROGRAMS_FOR_PAGE - 1;

export const ASSIGNAMENS_FOR_PAGE = 10;
export const ASSIGNAMENT_CURSOR_INDEX = ASSIGNAMENS_FOR_PAGE - 1;
