##  TERRITORIES 

### Recuperar todos territorios registrados
GET http://localhost:7070/api/v1/territories

### Recuperar un territorio por numero
GET http://localhost:7070/api/v1/territories/10

### Crear una territorio
POST http://localhost:7070/api/v1/territories
Content-Type: application/json

{
  "number": 10,
  "label": "Place beatiful",
  "limits": {
    "NORTH": "Mont",
    "SOUTH": "Rest",
    "EAST": "Sunny",
    "WEST": "River good"
  },
  "lastDateCompleted": "2023-03-1"
}

### Actualizar un territorio
PATCH http://localhost:7070/api/v1/territories/10
Content-Type: application/json

{
  "lastDateCompleted": "2023-09-1"
}

### Reemplazar lugares de encuentro en un territorio
PUT http://localhost:7070/api/v1/territories/10/meeting-places
Content-Type: application/json

{
  "meetingPlaces": [
    { "place": "Place 1", "latitude": "7.841722", "longitude": "-72.226129" },
    { "place": "Place 2", "latitude": "7.841722", "longitude": "72.226129" },
    { "place": "Place 3", "latitude": "7.841722", "longitude": "72.226129" }
  ]
}

### Borrar un territorio
DELETE http://localhost:7070/api/v1/territories/130928d6-c4a1-42c3-8d54-31f70734b6d3


## MEETING PLACES

### Modificar lugar de encuentro
PATCH http://localhost:7070/api/v1/meeting-places/5b2dfbcf-37d8-4a55-94ce-cfc1330a021c
Content-Type: application/json

{
  "place": "Place Update",
  "latitude": "8.841722", 
  "longitude": "-82.226129"
}

### Borrar lugar de encuentro
DELETE http://localhost:7070/api/v1/meeting-places/83859656-fe69-48ab-bf51-68bdae0c45b4


### Reemplazar disponibilidad del lugar de encuentro
PUT http://localhost:7070/api/v1/meeting-places/5b2dfbcf-37d8-4a55-94ce-cfc1330a021c/availability
Content-Type: application/json

{
  "phone": "0000-0000000",
  "fieldService": true,
  "availability": {
    "SATURDAY": { "frequency": "2 week", "moment": "MORNING" },
    "TUESDAY": { "frequency": "every", "moment": "AFTERNOON" }
  }
}

### Borrar disponiblidad del lugar de encuentro
DELETE http://localhost:7070/api/v1/meeting-places/3179f605-4d64-4f6b-b80b-9d9843149aa2/availability


## CONDUCTORS 

### Recuperar lista de conductores
GET http://localhost:7070/api/v1/conductors

### Recuperar conductor por id
GET http://localhost:7070/api/v1/conductors/6691fdca-7548-4c3d-8703-3846b2d8a0cd

### Crear un conductor
POST http://localhost:7070/api/v1/conductors
Content-Type: application/json

{
  "name": "Julio A.",
  "mobilePhone": "3333-000000",
  "serviceGroup": 3,
  "privilege": "QUALIFIED_BROTHER"
}

### Actualizar un conductor
PATCH http://localhost:7070/api/v1/conductors/6691fdca-7548-4c3d-8703-3846b2d8a0cd
Content-Type: application/json

{
  "name": "Julio Amoroso",
  "mobilePhone": "1111-000000",
  "serviceGroup": 1,
  "privilege": "GROUP_SERVANT"
}

### Borrar un conductor
DELETE http://localhost:7070/api/v1/conductors/5d74a457-bcc3-435e-9418-fce7ad39da68


### Reemplazar disponibilidad del conductor
PUT http://localhost:7070/api/v1/conductors/6691fdca-7548-4c3d-8703-3846b2d8a0cd/availability
Content-Type: application/json

{
  "SATURDAY": { "frequency": "2 week", "moment": "MORNING" },
  "TUESDAY": { "frequency": "every", "moment": "AFTERNOON" }
}

### Borrar disponiblidad del conductor
DELETE http://localhost:7070/api/v1/conductors/6691fdca-7548-4c3d-8703-3846b2d8a0cd/availability


## REGISTRY PERIODS

### Crear un periodo de registro
POST http://localhost:7070/api/v1/registries/periods
Content-Type: application/json

{
  "description": "New period of preach"
}

### Actualizar un periodo de registro
PATCH http://localhost:7070/api/v1/registries/periods/424ec997-f02e-4b77-8384-1816432c9038
Content-Type: application/json

{
  "description": "Special campain",
  "finishDate": "2023-06-23"
}

### Finalizar periodo de registro actual
POST http://localhost:7070/api/v1/registries/periods/finish

### Borrar un periodo de registro
DELETE http://localhost:7070/api/v1/registries/periods/4d43b5b5-cc78-41f7-b068-461fd7094ece

## REGISTRIES 

### Recuperar los registros del territorio
GET http://localhost:7070/api/v1/territories/10/registries

### Recuperar el ultimo registro del territorio
GET http://localhost:7070/api/v1/territories/10/registries?last=true

### Crear un registro
### TODO: Asegurar el maximo de registros por periodo
POST http://localhost:7070/api/v1/territories/10/registries
Content-Type: application/json

{
  "assignedToId": "aeae0ff8-f5b0-46a1-b844-79dbabe9c951",
  "dateAssigned": "2023-08-1"
}

### Actualizar como completado el último registro del territorio con la fecha de hoy
POST http://localhost:7070/api/v1/territories/10/registries/complete

### Actualizar el ultimo registro del territorio
### FIXME: Asegurar que la fecha de completado es mayor a la de asignación
PATCH http://localhost:7070/api/v1/territories/10/registries?last=true
Content-Type: application/json

{
  "assignedToId": "b54ff557-eb62-4fe1-bcc8-c62088a980df",
  "dateAssigned": "2023-7-20",
  "dateCompleted": "2023-8-20"
}

### Actualizar un registro
PATCH http://localhost:7070/api/v1/registries/424ec997-f02e-4b77-8384-1816432c9038
Content-Type: application/json

{
  "assignedTo": "Junior Publisher",
  "dateCompleted": "2023-7-20"
}

### Borrar un registro
DELETE http://localhost:7070/api/v1/registries/4d43b5b5-cc78-41f7-b068-461fd7094ece

## PROGRAM

### Crear un programa de predicación
POST http://localhost:7070/api/v1/programs
Content-Type: application/json

{
  "week": "2023-09-13"
}

### Recuperar el programa actual completo
GET http://localhost:7070/api/v1/programs

### Recuperar el programa completo por identificador
GET http://localhost:7070/api/v1/programs/4d43b5b5-cc78-41f7-b068-461fd7094ece

### Actualizar un programa de predicación
PATCH http://localhost:7070/api/v1/programs/4d43b5b5-cc78-41f7-b068-461fd7094ece
Content-Type: application/json

{
  "week": "2023-09-13"
}

### Borrar un programa de predicación
DELETE http://localhost:7070/api/v1/programs/4d43b5b5-cc78-41f7-b068-461fd7094ece

## ASSIGNAMENT

### Crear una asignación
### Si no envias el identificador el programa se asignará programa actual
POST http://localhost:7070/api/v1/programs/assignaments
Content-Type: application/json

{
  "meetingPlaceId": "a30bc7b6-7d96-4e13-b0b3-f34e913d7f89",
  "conductorId": "aeae0ff8-f5b0-46a1-b844-79dbabe9c951",
  "date": "2023-08-1",
}

### Actualizar una asignación
PATCH http://localhost:7070/api/v1/programs/assignaments/b54ff557-eb62-4fe1-bcc8-c62088a980df
Content-Type: application/json

{
  "meetingPlaceId": "a30bc7b6-7d96-4e13-b0b3-f34e913d7f89",
  "conductorId": "aeae0ff8-f5b0-46a1-b844-79dbabe9c951",
  "date": "2023-09-1",
}

### Borrar una asignación
DELETE http://localhost:7070/api/v1/programs/assignaments/b54ff557-eb62-4fe1-bcc8-c62088a980df
