##  TERRITORIES 

### Recuperar todos territorios
GET http://localhost:7070/api/v1/territories

### Recuperar todos territorios disponibles
GET http://localhost:7070/api/v1/territories?available=true

### Recuperar un territorio por numero
GET http://localhost:7070/api/v1/territories/10

### Crear una territorio
POST http://localhost:7070/api/v1/territories
Content-Type: application/json

{
  "number": 10,
  "label": "Place beatiful",
  "limits": {
    "NORTH": "Mont",
    "SOUTH": "Rest",
    "EAST": "Sunny",
    "WEST": "River good"
  },
  "lastDateCompleted": "2023-03-1"
}

### Actualizar un territorio
PATCH http://localhost:7070/api/v1/territories/10
Content-Type: application/json

{
  "lastDateCompleted": "2023-09-1"
}

### Reemplazar lugares de encuentro en un territorio
PUT http://localhost:7070/api/v1/territories/10/meeting-places
Content-Type: application/json

{
  "meetingPlaces": [
    { "place": "Place 1", "latitude": "7.841722", "longitude": "-72.226129" },
    { "place": "Place 2", "latitude": "7.841722", "longitude": "72.226129" },
    { "place": "Place 3", "latitude": "7.841722", "longitude": "72.226129" }
  ]
}

### Borrar un territorio
DELETE http://localhost:7070/api/v1/territories/130928d6-c4a1-42c3-8d54-31f70734b6d3


## MEETING PLACES

### Modificar lugar de encuentro
PATCH http://localhost:7070/api/v1/meeting-places/5b2dfbcf-37d8-4a55-94ce-cfc1330a021c
Content-Type: application/json

{
  "place": "Place Update",
  "latitude": "8.841722", 
  "longitude": "-82.226129"
}

### Borrar lugar de encuentro
DELETE http://localhost:7070/api/v1/meeting-places/83859656-fe69-48ab-bf51-68bdae0c45b4


### Reemplazar disponibilidad del lugar de encuentro
PUT http://localhost:7070/api/v1/meeting-places/5b2dfbcf-37d8-4a55-94ce-cfc1330a021c/availability
Content-Type: application/json

{
  "phone": "0000-0000000",
  "fieldService": true,
  "availability": {
    "SATURDAY": { "frequency": "2 week", "moment": "MORNING" },
    "TUESDAY": { "frequency": "every", "moment": "AFTERNOON" }
  }
}

### Borrar disponiblidad del lugar de encuentro
DELETE http://localhost:7070/api/v1/meeting-places/3179f605-4d64-4f6b-b80b-9d9843149aa2/availability


## CONDUCTORS 

### Recuperar lista de conductores
GET http://localhost:7070/api/v1/conductors

### Recuperar conductor por id
GET http://localhost:7070/api/v1/conductors/6691fdca-7548-4c3d-8703-3846b2d8a0cd

### Crear un conductor
POST http://localhost:7070/api/v1/conductors
Content-Type: application/json

{
  "name": "Julio A.",
  "mobilePhone": "3333-000000",
  "serviceGroup": 3,
  "privilege": "QUALIFIED_BROTHER"
}

### Actualizar un conductor
PATCH http://localhost:7070/api/v1/conductors/6691fdca-7548-4c3d-8703-3846b2d8a0cd
Content-Type: application/json

{
  "name": "Julio Amoroso",
  "mobilePhone": "1111-000000",
  "serviceGroup": 1,
  "privilege": "GROUP_SERVANT"
}

### Borrar un conductor
DELETE http://localhost:7070/api/v1/conductors/5d74a457-bcc3-435e-9418-fce7ad39da68


### Reemplazar disponibilidad del conductor
PUT http://localhost:7070/api/v1/conductors/6691fdca-7548-4c3d-8703-3846b2d8a0cd/availability
Content-Type: application/json

{
  "SATURDAY": { "frequency": "2 week", "moment": "MORNING" },
  "TUESDAY": { "frequency": "every", "moment": "AFTERNOON" }
}

### Borrar disponiblidad del conductor
DELETE http://localhost:7070/api/v1/conductors/6691fdca-7548-4c3d-8703-3846b2d8a0cd/availability


## REGISTRY PERIODS

### Crear un periodo de registro
POST http://localhost:7070/api/v1/registries/periods
Content-Type: application/json

{
  "description": "New period of preach"
}

### Finalizar periodo actual y crear nuevo periodo
POST http://localhost:7070/api/v1/registries/periods/finish-and-init
Content-Type: application/json

{
  "description": "Period of preach before finish"
}

### Actualizar un periodo de registro
PATCH http://localhost:7070/api/v1/registries/periods/f07abbd9-157a-4ac6-987d-b7ec28f63036
Content-Type: application/json

{
  "description": "Special campain",
  "finishDate": "2023-09-23"
}

### Finalizar periodo de registro actual
POST http://localhost:7070/api/v1/registries/periods/finish

### Borrar un periodo de registro
DELETE http://localhost:7070/api/v1/registries/periods/292edda1-ea9e-4ed5-a39b-c77c31fed6e5

## REGISTRIES 

### Recuperar los registros del territorio
GET http://localhost:7070/api/v1/territories/10/registries

### Recuperar el ultimo registro del territorio
GET http://localhost:7070/api/v1/territories/10/registries?last=true

### Crear un registro
### TODO: Asegurar el maximo de registros por periodo
POST http://localhost:7070/api/v1/territories/10/registries
Content-Type: application/json

{
  "assignedToId": "6691fdca-7548-4c3d-8703-3846b2d8a0cd",
  "assignedDate": "2023-08-1"
}

### Actualizar como completado el último registro del territorio con la fecha de hoy
POST http://localhost:7070/api/v1/territories/10/registries/completion

### Actualizar el ultimo registro del territorio
### FIXME: Asegurar que la fecha de completado es mayor a la de asignación
PATCH http://localhost:7070/api/v1/territories/1/registries?last=true
Content-Type: application/json

{
  "assignedToId": "d04e57f9-1f55-40fa-b9a2-106193bbafdf",
  "assignedDate": "2023-8-20",
  "completionDate": "2023-9-20"
}

### Actualizar un registro
PATCH http://localhost:7070/api/v1/registries/25e6a514-ee5f-4301-a84f-48a80072db2c
Content-Type: application/json

{
  "assignedToId": "aceb5fb4-22c3-4ef3-a5c6-f3572c770fa6",
  "assignedDate": "2023-7-20",
  "completionDate": "2023-7-20"
}

### Borrar un registro
DELETE http://localhost:7070/api/v1/registries/4d43b5b5-cc78-41f7-b068-461fd7094ece

## PROGRAMS

### Recuperar todos programas completos sin incluir los futuros
### Tipo de paginación: cursor-based pagination
### Por defecto cada página contiene 2 programas
### Ordenado por fecha de inicio de forma desendiente
GET http://localhost:7070/api/v1/programs

### Recuperar todos programas completos desde cursor
GET http://localhost:7070/api/v1/programs?cursor=b032f09a-8ece-4bbe-b4d6-6338b0807e99

### Recuperar todos programas completos incluyendo los futuros
GET http://localhost:7070/api/v1/programs?future=true

### Recuperar todos programas completos incluyendo los futuros desde cursor
GET http://localhost:7070/api/v1/programs?future=true&cursor=77df4698-a0ef-428b-8b0a-8ef8d70c1040

### Recuperar el programa actual completo
GET http://localhost:7070/api/v1/programs?current=true

### Recuperar el programa completo por identificador
GET http://localhost:7070/api/v1/programs/b032f09a-8ece-4bbe-b4d6-6338b0807e99

### Crear un programa
### TODO: Asegurarse que no haya dos programas para una misma semana
POST http://localhost:7070/api/v1/programs
Content-Type: application/json

{
  "sinceWeek": "2024-01-13",
  "daysDuration": 7
}

### Actualizar un programa
PATCH http://localhost:7070/api/v1/programs/97704c93-55a7-4766-a2ec-97171ee8735a
Content-Type: application/json

{
  "sinceWeek": "2023-09-17",
  "untilWeek": "2023-09-23"
}

### Borrar un programa
DELETE http://localhost:7070/api/v1/programs/d0948a4d-80e1-4262-9c19-aefe6de51468

## ASSIGNAMENTS

### Recuperar todas las asignaciones sin incluir las futuras
### Tipo de paginación: cursor-based pagination
### Por defecto cada página contiene 10 asignaciones
### Ordenado por fecha de asignaciones de forma desendiente
GET http://localhost:7070/api/v1/programs/assignaments

### Recuperar todas las asignaciones desde cursor
GET http://localhost:7070/api/v1/programs/assignaments?cursor=4d43b5b5-cc78-41f7-b068-461fd7094ece

### Recuperar todas las asignaciones incluyendo las futuras
GET http://localhost:7070/api/v1/programs/assignaments?future=true

### Crear una asignación
### Si no envias el identificador el programa se asignará programa actual
POST http://localhost:7070/api/v1/programs/assignaments
Content-Type: application/json

{
  "meetingPlaceId": "a30bc7b6-7d96-4e13-b0b3-f34e913d7f89",
  "conductorId": "aeae0ff8-f5b0-46a1-b844-79dbabe9c951",
  "date": "2023-08-1",
}

### Actualizar una asignación
PATCH http://localhost:7070/api/v1/programs/assignaments/b54ff557-eb62-4fe1-bcc8-c62088a980df
Content-Type: application/json

{
  "meetingPlaceId": "a30bc7b6-7d96-4e13-b0b3-f34e913d7f89",
  "conductorId": "aeae0ff8-f5b0-46a1-b844-79dbabe9c951",
  "date": "2023-09-1",
}

### Borrar una asignación
DELETE http://localhost:7070/api/v1/programs/assignaments/b54ff557-eb62-4fe1-bcc8-c62088a980df
