name: '🐢 Node'

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
      - name: Setup Node ⚙️
        uses: ./.github/actions/setup-node
      - name: Build typescript 📦
        env:
          SQLITE_DATABASE: ${{ secrets.SQLITE_DATABASE }}
        run: node --run build && find dist/main.js
      - name: Lint code 💅
        run: node --run lint
      - name: Run tests ✅
        run: node --run test
